version: '3.9'

services:
  opensis-db:
    image: mariadb:10.5
    container_name: opensis-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secrets#$"
      MYSQL_DATABASE: "openSIS"
      MYSQL_USER: "openSIS_rw"
      MYSQL_PASSWORD: "Op3nS!S"
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./MYSQL/mysql-init:/docker-entrypoint-initdb.d  # Init scripts
      - ./MYSQL/mysql-config:/etc/mysql/conf.d/strict_mode.cnf  # Custom MySQL config
    networks:
      opensis-nw:
        aliases:
          - opensis

  opensis-ui:
    image: opensis-i
    container_name: opensis-ui
    depends_on:
      - opensis-db
    ports:
      - "8080:80"
    networks:
      opensis-nw:
        aliases:
          - opensis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
       - "./rules.yml:/etc/prometheus/rules.yml"
    networks:
      opensis-nw:
        aliases:
          - prometheus
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      opensis-nw:
        aliases:
          - node-exporter
    ports:
      - "9100:9100"
    
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - opensis-nw
    ports:
      - 9093:9093

networks:
  opensis-nw:
    driver: bridge

volumes:
  db_data:  # Named volume for MariaDB persistence


